refactor [workspace selector]: Show search input only if workspace selector has more than 5 items
mParticle/aquarium pull request #130
Opened 2024-03-08 22:36 UTC by nastyastavitskaya

## Instructions
1. PR target branch should be against `main`
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

## Summary
- Updating `WorkspaceSelector` to only show search input, if the selector has more than 5 items to enhance the UX.
## Testing Plan
- [ ] Was this tested locally? If not, explain why.
- Run the story tests for GlobalNavigation with different numbers of items in the workspace selector.
## Reference Issue (For mParticle employees only.  Ignore if you are an outside contributor)
- Closes https://mparticle-eng.atlassian.net/browse/UNI-220

2024-03-08 23:24 UTC, jared-dickman approved these changes
seems legit

2024-03-08 23:24 UTC, jared-dickman commented
might need to adjust your branch name to have the checks pass

2024-03-11 15:39 UTC, nastyastavitskaya commented
> might need to adjust your branch name to have the checks pass

so it's complaining about the `branch` name? I thought it was not happy with the PR title, which I changed since this check failed, but it is still unhappy 😞

2024-03-11 19:13 UTC, tibuurcio approved these changes

2024-03-14 04:15 UTC, jared-dickman commented
would be great to add a test in a story 😉

2024-03-14 04:42 UTC, jared-dickman commented on src/components/navigation/GlobalNavigation/WorkspaceSelector/WorkspaceSelector.tsx
> +  const hasSearchInput = menuItems.filter(item => !!item.label).length > 5
might want to add a check for an existing search term, the search bar seems to disappear when no results are found

2024-03-14 19:55 UTC, jared-dickman requested changes
**issue** search input disappears when no results are found

this will be considered a bug and should be addressed with a story test in this pr

2024-03-14 22:19 UTC, nastyastavitskaya commented on src/components/navigation/GlobalNavigation/WorkspaceSelector/WorkspaceSelector.tsx
> +  const hasSearchInput = menuItems.filter(item => !!item.label).length > 5
oof, yes! You're right, great 🐛 catch

2024-03-19 18:49 UTC, jared-dickman commented
@tibuurcio this presents an interesting challenge, i cant check out this branch because its on a forked branch. 

@nastyastavitskaya it currently says in [Contributing](https://github.com/mParticle/aquarium/blob/c056d9f27b89096334f7570b64a123da2173d8fc/CONTRIBUTING.md#L1) to clone the repo, do you know where it said to fork? possibly that was changed recently?

2024-03-19 18:51 UTC, nastyastavitskaya commented
> @tibuurcio this presents an interesting challenge, i cant check out this branch because its on a forked branch.
> 
> @nastyastavitskaya it currently says in [Contributing](https://github.com/mParticle/aquarium/blob/c056d9f27b89096334f7570b64a123da2173d8fc/CONTRIBUTING.md#L1) to clone the repo, do you know where it said to fork? possibly that was changed recently?

was changed 4 days ago:
<img width="1099" alt="Screenshot 2024-03-19 at 11 51 03 AM" src="https://github.com/mParticle/aquarium/assets/12608980/a9b977fb-6ff2-472a-8f36-1bb4457bf747">

2024-03-19 18:53 UTC, jared-dickman commented
ah-ha makes sense

probably best for you to remove the forked repo, and clone instead, allowing the rest of the team to checkout the branches locally

2024-03-19 18:53 UTC, nastyastavitskaya commented
> @tibuurcio this presents an interesting challenge, i cant check out this branch because its on a forked branch.
> 
> @nastyastavitskaya it currently says in [Contributing](https://github.com/mParticle/aquarium/blob/c056d9f27b89096334f7570b64a123da2173d8fc/CONTRIBUTING.md#L1) to clone the repo, do you know where it said to fork? possibly that was changed recently?

I guess I can close this PR, clone the repo instead of forking, and then create a new PR from it.

2024-03-19 18:54 UTC, closed without merging