chore: update design tokens
mParticle/aquarium pull request #311
Opened 2024-06-25 15:38 UTC by jared-dickman

## Instructions

1. PR target branch should be against `main`
2. PR title name should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-title-check.yml
3. PR branch prefix should follow this format: https://github.com/mParticle/mparticle-workflows/blob/main/.github/workflows/pr-branch-check-name.yml

## Summary
- Use new tokens as provided by design

2024-06-26 22:22 UTC, ZoeAstra approved these changes
Looks good, tested locally and fixes the color issues.

2024-06-27 14:53 UTC, jared-dickman commented on src/styles/_variables.css
> +  --color-icon-hover: rgba(0, 0, 0, 0.88);
**ISSUE** these variables should not be changed...

2024-06-27 14:53 UTC, tibuurcio requested changes

2024-06-27 14:53 UTC, tibuurcio commented on src/styles/_variables.css
> +  --color-icon-hover: rgba(0, 0, 0, 0.88);
This is broken, we need to address it before merging

2024-09-17 16:27 UTC, closed without merging